config/routes.rb
Rails.application.routes.draw do
  root to:"root#root"

  namespace :api, defaults: {format: :json} do
    resource :session, only: [:create, :show, :destroy]

    resources :users, only: [:index, :show, :update, :create] do
      resources :likes, only: [:index]
    end

    resources :playlists, only: [:create, :index, :show, :update, :destroy]

    resources :songs, only: [:create, :index, :show, :update, :destroy]
    resources :comments, only: [:create, :index, :show, :destroy]

    resources :playlist_songs, only: [:create, :index, :destroy]
    resources :likes, only: [:index, :create, :destroy]

    get 'search', to: "searches#index"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :playlists, dependent: :destroy
  has_many :songs, class_name: "Song", foreign_key: :uploader_id, dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: :user_id, dependent: :destroy
  has_many :likes, class_name: "Like", foreign_key: :user_id, dependent: :destroy
  has_many :liked_songs, through: :likes, source: :song

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def image_url=(image_url)
    unless self.image.exists?
      self.image = image_url
    end
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.includes(:songs, :playlists, :liked_songs).find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if  @user.save
      sign_in(@user)
      render :show
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      render json: @user
    else
      render json: @user.errors.full_messages, status: 422
    end
    
  end

  private
  def user_params
    params.require(:user).permit(:password, :username, :image, :image_url)
  end
  
end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#   skip_before_action :require_signed_in!, only: [:new, :create]

#   wrap_parameters :user, include: [:password, :username, :image]
#   def new
#     @user = User.new
#   end

#   def create
#     @user = User.new(user_params)
#     if @user.save
#       sign_in(@user)
#       # render json: "welcome new dood"
#       redirect_to "/#/users/#{@user.id}"
#     else
#       flash.now[:errors] = @user.errors.full_messages
#       render :new
#     end
#   end

#   def show
#     @user = User.find(params[:id])
#     # @playlists = @user.playlists
#     render :show
#   end

#   private
#   def user_params
#     params.require(:user).permit(:password, :username, :image)
#   end
# end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= render "layouts/errors" %>

<form class="users-form" action="<%= users_url %>" method="post" enctype="multipart/form-data">
  <%= auth_token_input %>
  <label class="user-label">
    <span>Username</span>
    <input type="text" name="user[username]" value="">
  </label>

  <label class="user-label">
    <span>Password</span>
    <input type="password" name="user[password]" value="">
  </label>

  <label class="image-label">
  <span>Image</span>
  <input type="file" name="user[image]" id="input-post-image">
</label>


  <input class="sign-up-button" type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>
<br>
<h3>Your Playlists</h3>
<ul>
  <% @user.playlists.each do |playlist| %>
    <li>
      <%= link_to playlist.name, playlist_url(playlist) %> <%= button_to "Delete Playlist", playlist_url(playlist), method: :delete %>
    </li>
  <% end %>
</ul>

<h3>Your Songs</h3>
<ul>
  <% @user.songs.each do |song| %>
    <li><%= link_to song.title, song_url(song) %>  <%= button_to "Delete Song", song_url(song), method: :delete %></li>
  <% end %>
</ul>


<%= link_to "Create Playlist", new_playlist_url %>
<%= link_to "Create Song", new_song_url %>

<br>
<%=render "layouts/errors"%>