config/routes.rb
Rails.application.routes.draw do
  root to:"root#root"

  namespace :api, defaults: {format: :json} do
    resource :session, only: [:create, :show, :destroy]

    resources :users, only: [:index, :show, :update, :create] do
      resources :likes, only: [:index]
    end

    resources :playlists, only: [:create, :index, :show, :update, :destroy]

    resources :songs, only: [:create, :index, :show, :update, :destroy]
    resources :comments, only: [:create, :index, :show, :destroy]

    resources :playlist_songs, only: [:create, :index, :destroy]
    resources :likes, only: [:index, :create, :destroy]

    get 'search', to: "searches#index"
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  include PgSearch

  pg_search_scope :search_by_all, against: [:title, :artist, :album]

  belongs_to :uploader, class_name: "User", foreign_key: :uploader_id
  has_many :playlist_songs, class_name: "PlaylistSong", foreign_key: :song_id

  has_many :playlists, through: :playlist_songs, source: :playlist
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user


  has_attached_file :audio,
    default_url: "default1.mp3"

  validates_attachment_content_type :audio,
  :content_type => [
    'audio/mpeg',
    'audio/x-mpeg',
    'audio/mp3',
    'audio/x-mp3',
    'audio/mpeg3',
    'audio/x-mpeg3',
  ]

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/


  def audio_url=(audio_url)
    unless self.audio.exists?
      self.audio = audio_url
    end
  end

  def days_ago
    ((Time.now - self.created_at.to_time)/86400).to_i
  end

end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  
  def index
    @songs = params[:user_id] ? Song.where(uploader_id: params[:user_id]) : Song.all
    render :index
  end

  def create
    @song = current_user.songs.new(song_params)
    if @song.save
      render :show
    else
      render json: @song.errors.full_messages, status: 422
    end
  end

  def show
    @song = Song.includes(comments: :user).find(params[:id])
    render :show
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy
    render json: song
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(song_params)
      render :show
    else
      render json: @song.errors.full_messages, status: 422
    end
  end

  private
  def song_params
    params.require(:song).permit(:title, :artist, :album, :playlists, :audio, :audio_url, :image)
  end

end

app/controllers/songs_controller.rb
# class SongsController < ApplicationController
#   before_action :prevent_delete, only: [:destroy, :edit, :update]
#   def new
#     @song = Song.new
#   end

#   def index
#     @songs = params[:user_id] ? User.find(params[:user_id]).songs : Song.all
#     render json: @songs 
#   end

#   def create
#     @song = current_user.songs.new(song_params)

#     if @song.save
#       redirect_to song_url(@song)
#     else
#       flash.now[:errors] = @playlist.errors.full_messages
#       render :new
#     end
#   end

#   def show
#     @song = Song.find(params[:id])
#     render :show
#   end

#   def destroy
#     song = Song.find(params[:id])
#     song.destroy
#     redirect_to user_url(current_user)
#   end

#   def edit
#     @song = Song.find(params[:id])
#   end

#   def update
#     @song = Song.find(params[:id])
#     if @song.update_attributes(song_params)
#       redirect_to song_url(@song)
#     else
#       flash.now[:errors] = @song.errors.full_messages
#       render :edit
#     end
#   end

#   private
#   def song_params
#     params.require(:song).permit(:title, :album, :artist)
#   end

#   def prevent_delete
#     song = Song.find(params[:id])
#     if current_user.id != song.uploader_id
#       redirect_to user_url(User.find(song.uploader_id))
#       flash[:errors] = ["You can't do that"]
#     end
#   end
# end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= render "layouts/errors" %>

<form action="<%= song_url(@song) %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="song[title]" value="<%= @song.title %>">
  </label>

  <label>
    Artist
    <input type="text" name="song[artist]" value="<%= @song.artist %>">
  </label>

  <label>
    Album
    <input type="text" name="song[album]" value="<%= @song.album %>">
  </label>

  <input type="submit" value="Update Song">
</form>

app/views/songs/new.html.erb
<h2>Create a Song</h2>

<%= render "layouts/errors" %>

<form action="<%= songs_url %>" method="post">
  <%= auth_token_input %>
  <label>
    Title
    <input type="text" name="song[title]" value="">
  </label>
  <label>
    Artist
    <input type="text" name="song[artist]" value="">
  </label>
  <label>
    Album
    <input type="text" name="song[album]" value="">
  </label>


  <input type="submit" value="Create">
</form>

app/views/songs/show.html.erb
<h1><%= link_to @song.uploader.username, user_url(@song.uploader) %>'s song</h1>

<h3> <%= @song.title %> </h3> <%= link_to "Edit song", edit_song_url(@song) %>
<ul>
  <li> Artist: <%= @song.artist %> </li>
  <li> Album: <%= @song.album %> </li>
</ul>

<br>
<%= render "playlist_songs/form", {song: @song}%>

<br>
<h4>Belongs to the following playlists:</h4>
<ul>
  <% @song.playlists.each do |playlist| %>
    <li>
      <%= link_to playlist.name, playlist_url(playlist) %>
    </li>
  <% end %>
</ul>

<h4>Comments</h4>
<ul>
  <% @song.comments.each do |comment| %>
    <% user = User.find(comment.user_id) %>
    <li> <%= comment.body %> - <%= link_to user.username, user_url(user) %> </li>
  <% end %>
</ul>

<%= render "comments/form", {commentable_type: "Song"}%>