config/routes.rb
Rails.application.routes.draw do
  root to:"root#root"

  namespace :api, defaults: {format: :json} do
    resource :session, only: [:create, :show, :destroy]

    resources :users, only: [:index, :show, :update, :create] do
      resources :likes, only: [:index]
    end

    resources :playlists, only: [:create, :index, :show, :update, :destroy]

    resources :songs, only: [:create, :index, :show, :update, :destroy]
    resources :comments, only: [:create, :index, :show, :destroy]

    resources :playlist_songs, only: [:create, :index, :destroy]
    resources :likes, only: [:index, :create, :destroy]

    get 'search', to: "searches#index"
  end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, :user_id, presence: true

  belongs_to :user

  has_many :playlist_songs, class_name: "PlaylistSong", foreign_key: :playlist_id

  has_many :songs, through: :playlist_songs, source: :song
  has_many :comments, as: :commentable, dependent: :destroy

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/

    def days_ago
      ((Time.now - self.created_at.to_time)/86400).to_i
    end
end

app/controllers/api/playlists_controller.rb
class Api::PlaylistsController < ApplicationController

  def index
    if current_user
      @playlists = current_user.playlists
    else
      @playlists = Playlist.all
    end

    render :index
  end

  def create
    @playlist = current_user.playlists.new(playlist_params)
    @playlist.user_id = current_user.id
    if @playlist.save
      render :show
    else
      render json: @playlists.errors.full_messages, status: 422
    end
  end

  def show
    @playlist = Playlist.includes(:songs).find(params[:id])
    render :show
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    render json: @playlist
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update_attributes(playlist_params)
      render json: @playlist
    else
      render json: @playlist.errors.full_messages, status: 422
    end
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name, :image)
  end

end

app/controllers/playlists_controller.rb
# class PlaylistsController < ApplicationController
#   before_action :prevent_delete, only: [:destroy, :edit, :update]
#   def new
#     @playlist = Playlist.new
#     render :new
#   end

#   def create
#     @playlist = current_user.playlists.new(playlist_params)
    
#     if @playlist.save
#       redirect_to playlist_url(@playlist)
#     else
#       flash.now[:errors] = @playlist.errors.full_messages
#       render :new
#     end
#   end

#   def show
#     @playlist = Playlist.find(params[:id])
#     render :show
#   end

#   def destroy
#     @playlist = Playlist.find(params[:id])
#     @playlist.destroy
#     redirect_to user_url(current_user)
#   end

#   def edit
#     @playlist = Playlist.find(params[:id])
#   end

#   def update
#     @playlist = Playlist.find(params[:id])
#     if @playlist.update_attributes(playlist_params)
#       redirect_to playlist_url(@playlist)
#     else
#       flash.now[:errors] = @playlist.errors.full_messages
#       render :edit
#     end
#   end

#   private
#   def playlist_params
#     params.require(:playlist).permit(:name)
#   end

#   def prevent_delete
#     playlist = Playlist.find(params[:id])
#     if current_user.id != playlist.user_id
#       redirect_to user_url(User.find(playlist.user_id))
#       flash[:errors] = ["You can't do that"]
#     end
#   end
# end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/edit.html.erb
<h2>Edit Playlist</h2>

<%= render "layouts/errors" %>

<form action="<%= playlist_url(@playlist) %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="patch">

  <label>
    Playlist Name
    <input type="text" name="playlist[name]" value="<%= @playlist.name %>">
  </label>

  <input type="submit" value="Update Playlist">
</form>

app/views/playlists/new.html.erb
<h2>Create a Playlist</h2>

<%= render "layouts/errors" %>

<form action="<%= playlists_url %>" method="post">
  <%= auth_token_input %>
  <label>
    Playlist Name
    <input type="text" name="playlist[name]" value="">
  </label>


  <input type="submit" value="Create">
</form>

app/views/playlists/show.html.erb
<h1> <%= link_to @playlist.user.username, user_url(@playlist.user_id) %>'s Playlist Show Page</h1>
<br>
<h3> <%= @playlist.name %> </h3> <%= link_to "Edit playlist", edit_playlist_url(@playlist) %>

<h4>Has the following songs:</h4>
<ul>
  <% @playlist.songs.each do |song| %>
    <li>
      <% p_song = PlaylistSong.find_by({song_id:song.id, playlist_id:@playlist.id}) %>
      <%= link_to song.title, song_url(song) %> - <%= button_to "Remove from list",
                                                  playlist_song_url(p_song), method: :delete%>
    </li>
  <% end %>
</ul>

<h3>Comments</h3>
<% @playlist.comments.each do |comment| %>
  <% user = User.find(comment.user_id) %>
  <li><%= comment.body %> - <%= link_to user.username, user_url(user) %></li>
<% end %>
<%= render "comments/form", {commentable_type: "Playlist"} %>