config/routes.rb
Rails.application.routes.draw do
  root to:"root#root"

  namespace :api, defaults: {format: :json} do
    resource :session, only: [:create, :show, :destroy]

    resources :users, only: [:index, :show, :update, :create] do
      resources :likes, only: [:index]
    end

    resources :playlists, only: [:create, :index, :show, :update, :destroy]

    resources :songs, only: [:create, :index, :show, :update, :destroy]
    resources :comments, only: [:create, :index, :show, :destroy]

    resources :playlist_songs, only: [:create, :index, :destroy]
    resources :likes, only: [:index, :create, :destroy]

    get 'search', to: "searches#index"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, presence: true

  belongs_to :user
  belongs_to :commentable, polymorphic: true

  def days_ago
  	((Time.now - self.created_at.to_time)/86400).to_i
  end

  def at_time
  	hour = created_at.time.hour
  	min = created_at.time.min
  	time = ""

  	if hour.to_i >= 10
	  	time = "#{created_at.time.hour} : #{created_at.time.min}"
	  else
	  	time = "0#{created_at.time.hour} : #{created_at.time.min}"
	  end

	  time

  end
  
end

app/models/like.rb
class Like < ActiveRecord::Base

	validates :user_id, :song_id, presence: true

	belongs_to :user
	belongs_to :song




end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, :user_id, presence: true

  belongs_to :user

  has_many :playlist_songs, class_name: "PlaylistSong", foreign_key: :playlist_id

  has_many :songs, through: :playlist_songs, source: :song
  has_many :comments, as: :commentable, dependent: :destroy

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/

    def days_ago
      ((Time.now - self.created_at.to_time)/86400).to_i
    end
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  validates :song_id, :playlist_id, presence: true

  belongs_to :playlist, class_name: "Playlist", foreign_key: :playlist_id
  belongs_to :song, class_name: "Song", foreign_key: :song_id
  

end

app/models/session.rb
class Session < ActiveRecord::Base
  validates :session_token, :user_id, presence: true
  validates :session_token, uniqueness: true

  def create_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  include PgSearch

  pg_search_scope :search_by_all, against: [:title, :artist, :album]

  belongs_to :uploader, class_name: "User", foreign_key: :uploader_id
  has_many :playlist_songs, class_name: "PlaylistSong", foreign_key: :song_id

  has_many :playlists, through: :playlist_songs, source: :playlist
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user


  has_attached_file :audio,
    default_url: "default1.mp3"

  validates_attachment_content_type :audio,
  :content_type => [
    'audio/mpeg',
    'audio/x-mpeg',
    'audio/mp3',
    'audio/x-mp3',
    'audio/mpeg3',
    'audio/x-mpeg3',
  ]

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/


  def audio_url=(audio_url)
    unless self.audio.exists?
      self.audio = audio_url
    end
  end

  def days_ago
    ((Time.now - self.created_at.to_time)/86400).to_i
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :playlists, dependent: :destroy
  has_many :songs, class_name: "Song", foreign_key: :uploader_id, dependent: :destroy
  has_many :comments, class_name: "Comment", foreign_key: :user_id, dependent: :destroy
  has_many :likes, class_name: "Like", foreign_key: :user_id, dependent: :destroy
  has_many :liked_songs, through: :likes, source: :song

  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "missing-img.png"

  validates_attachment_content_type :image,
    :content_type => /\Aimage\/.*\Z/

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def image_url=(image_url)
    unless self.image.exists?
      self.image = image_url
    end
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def new
#     @comment = Comment.new
#   end

#   def create
#     @comment = current_user.comments.new(comment_params)
#     if @comment.save
#       if @comment.commentable_type == "Song"
#         redirect_to song_url(Song.find(@comment.commentable_id))
#       else
#         redirect_to playlist_url(Playlist.find(@comment.commentable_id))
#       end
#     else
#       flash.now[:errors] = @comment.errors.full_messages
#     end
#   end


#   private
#   def comment_params
#     params.require(:comment).permit(:body, :commentable_type, :commentable_id)
#   end
# end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
  	render :root
  end
end

app/controllers/songs_controller.rb
# class SongsController < ApplicationController
#   before_action :prevent_delete, only: [:destroy, :edit, :update]
#   def new
#     @song = Song.new
#   end

#   def index
#     @songs = params[:user_id] ? User.find(params[:user_id]).songs : Song.all
#     render json: @songs 
#   end

#   def create
#     @song = current_user.songs.new(song_params)

#     if @song.save
#       redirect_to song_url(@song)
#     else
#       flash.now[:errors] = @playlist.errors.full_messages
#       render :new
#     end
#   end

#   def show
#     @song = Song.find(params[:id])
#     render :show
#   end

#   def destroy
#     song = Song.find(params[:id])
#     song.destroy
#     redirect_to user_url(current_user)
#   end

#   def edit
#     @song = Song.find(params[:id])
#   end

#   def update
#     @song = Song.find(params[:id])
#     if @song.update_attributes(song_params)
#       redirect_to song_url(@song)
#     else
#       flash.now[:errors] = @song.errors.full_messages
#       render :edit
#     end
#   end

#   private
#   def song_params
#     params.require(:song).permit(:title, :album, :artist)
#   end

#   def prevent_delete
#     song = Song.find(params[:id])
#     if current_user.id != song.uploader_id
#       redirect_to user_url(User.find(song.uploader_id))
#       flash[:errors] = ["You can't do that"]
#     end
#   end
# end

app/controllers/users_controller.rb
# class UsersController < ApplicationController
#   skip_before_action :require_signed_in!, only: [:new, :create]

#   wrap_parameters :user, include: [:password, :username, :image]
#   def new
#     @user = User.new
#   end

#   def create
#     @user = User.new(user_params)
#     if @user.save
#       sign_in(@user)
#       # render json: "welcome new dood"
#       redirect_to "/#/users/#{@user.id}"
#     else
#       flash.now[:errors] = @user.errors.full_messages
#       render :new
#     end
#   end

#   def show
#     @user = User.find(params[:id])
#     # @playlists = @user.playlists
#     render :show
#   end

#   private
#   def user_params
#     params.require(:user).permit(:password, :username, :image)
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/playlist_songs_helper.rb
module PlaylistSongsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/app_stuff.html.erb
 <header class="header">
    <nav class="header-nav group">
      <% if signed_in? %>
        <% user_home = "/#/users/#{current_user.id}" %>
        <h1 class="header-logo">
          <a href=<%= user_home %>>Songstorm</a>
        </h1>
      <% else %>
        <% non_user_home = "/session/new" %>
        <h1 class="header-logo">
          <a href=<%= new_session_url %>>Songstorm</a>
        </h1>
      <% end %>

      <form class="search-bar">
      <input type="text" class="query" placeholder="Search songs, artists, albums" value="">
      <input type="submit" class="search">
      </form>

      <ul class="header-list group">
        <% if signed_in? %>
          <li>
            <a href="#/songs/new">Upload</a>
          </li>
          <li>
            <%= link_to "Home", "/#/users/#{current_user.id}" %>
          </li>
          <li>
            <a>
              <form class="sign_out" action="<%= session_url %>" method="post">
                <%= auth_token_input %>
                <input name="_method" type="hidden" value="delete">
                <input class="sign-out" type="submit" value="Sign Out">
              </form>
            </a>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_session_url %>
          </li>
          <li>
            <%= link_to "Sign Up", new_user_url %>
          </li>
        <% end %>

      </ul>
    </nav>
  </header>









  <footer class="footer group">
    <small class="footer-copy">
      &copy; 20X6 Sai K. Inc...I Have Laywers
    </small>
    <ul class="footer-links group">
      <% if signed_in? %>
        <li><a href="/#/users/<%= current_user.id %>">Home</a></li>
      <% end %>
      <li><a href="#">About</a></li>
      <li><a href="#">Privacy(jk it's a myth)</a></li>
    </ul>
  </footer>

  <div class="modal is-open">
  
    <form class="modal-form users-form" action="<%= session_url %>" method="post">
      <%= auth_token_input %>

      <span class="modal-close js-modal-close">&times;</span>
  
      <h1>Welcome</h1>
  
      <p>Please sign in to continue.</p>
  
      <div class="input">
        <label>
          <span>Username</span>
          <input type="text" name="user[username]" value="">
        </label>
      </div>
      
      <div class="input">
        <label>
          <span>Password</span>
          <input type="password" name="user[password]" value="">
      </label>
      </div>
      
      <div class="submit">
        <button>Sign In</button>
      
        <span class="button-alternative">or <strong class="js-modal-close">Cancel</strong></span>
      
      </div>
    </form>
  
    <div class="modal-screen js-modal-close"></div>
  </div>




<script>
$(function(){

  $("body").on("click", ".js-modal-open", function(event){
    event.preventDefault();
    $(".modal").addClass("is-open");
  });

  $("body").on("click", ".js-modal-close", function(event){
    event.preventDefault();
    $(".modal").removeClass("is-open");
  });

});
</script>












    <nav class="header-nav group">
      <% if Songstorm.currentUser.isSignedIn() %>
        <% user_home = "/#/users/"+Songstorm.currentUser.id %>
        <h1 class="header-logo">
          <a href=<%= user_home %>>Songstorm</a>
        </h1>
      <% else %>
        <% non_user_home = "/#/session/new" %>
        <h1 class="header-logo">
          <a href=<%= non_user_home %>>Songstorm</a>
        </h1>
      <% end %>

      <form class="search-bar">
      <input type="text" class="query" placeholder="Search songs, artists, albums" value="">
      <input type="submit" class="search">
      </form>

      <ul class="header-list group">
        <% if Songstorm.currentUser.isSignedIn() %>
          <li>
            <a href="#/songs/new">Upload</a>
          </li>
          <li>
             <% user_home = "/#/users/"+ Songstorm.currentUser.id %>
            <a href=<% user_home %>>Home</a>
          </li>
          <li>
            <a id="sign-out-link">Sign Out</a>
          </li>
        <% else %>
          <li>
            <a href="#/session/new">Sign In</a>
          </li>
          <li>
            <a href="#/users/new">Sign Up</a>
          </li>
        <% end %>

      </ul>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Songstorm</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

 

  <%= yield %>

  
</body>
</html>

app/views/layouts/extra.html.erb
  <!-- <% if signed_in? %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, :method => :delete %>
  <%= link_to "Home", user_url(current_user) %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %> -->